config/routes.rb
CalendarExample::Application.routes.draw do
  devise_for :users

  resource :calendar, only: [:show], controller: :calendar
  root to: "calendar#show"

  resources :events, only: [:show, :new, :index, :create]
  get '/events/:date', to: 'events#index'

  resources :day, only: [:show]
  #redirect_to :root unless params.require(:date) =~ /^\d{8}$/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def show
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @date = Time.zone.now
    start_of_day = @date.at_beginning_of_day
    end_of_day = @date.at_end_of_day
    @events = Event.where(date_and_time: start_of_day..end_of_day)
    @events_by_date = @events.group_by { |i| i.start_date.to_date }
    # @day = params [:date] ? Date.parse(params[:date]) : Date.today
  end

  def index
  @events = Event.group_by(&:date)

  end


  def calendar_params
    #params.require(:day).permit(:name, :date, :location)
    #params.require(:event).permit(:name, :date_and_time, :location)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @events = Event.new
  end

  def create
    @events = Event.new(event_params)
   if @events.save
      redirect_to root_path
   else
      render :new
   end
  end

  def index
    @day = Time.zone.now
    start_of_day = @day.at_beginning_of_day
    end_of_day = @day.at_end_of_day
    @events = Event.where(date_and_time: start_of_day..end_of_day)
  end

  def show
    @day = Time.zone.parse(params[:id])
    start_of_day = @day.at_beginning_of_day
    end_of_day = @day.at_end_of_day
   @events = Event.where(date_and_time: start_of_day..end_of_day)
  end

  private
  def event_params
    params.require(:event).permit(:name, :date_and_time, :location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
#    Calendar.new(self, date, block).table
    Event.new(name: "test event")
  end

  def events_for_day(day)
    Event.where(date_and_time: day)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/calendar/show.html.erb
<h1 id="daleytasks"> Daley Tasks</h1>
<div class="row">
  <div class="col-md-12 text-center">
    <div class="well controls">
      <%= link_to "Today", events_path, class: "btn btn-default" %>
      <%= link_to calendar_path(date: @date - 1.month), class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-backward"></i>
      <%end%>
      <h1 id="dateyear"> <%= "#{@date.strftime("%B")} #{@date.year}" %> </h1>
      <%= link_to calendar_path(date: @date + 1.month), class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-forward"></i>
      <%= link_to "Add Event", new_event_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class= "calendar", id="cal">
      <%= calendar @date do |date| %>
        <%= link_to date.day, "#{events_path}/#{date}" %>
            <% if @events_by_date[date] %>
              <ul>
              <% @events_by_date[date].each do |event| %>
                <li><%= link_to event.name, event %></li>
              <% end %>
              </ul>
          <% end %>
            <!-- <% Events.where(event_start_date: event_start_date..event_end_date).each do |event| %> -->
        <% end %>
          <!-- #highlight code here, helper method? -->
      <% end %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@events) do |f| %>
  <% if @events.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date_and_time %>
    <%= f.datetime_field :date_and_time %>

  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render 'form', event: @events %>

<%= link_to 'Show', @events %> |
<%= link_to 'Back', event_path %>

app/views/events/index.html.erb
  <div class="container">
    <h1 id="datetoday"> Day : <%= @day.strftime("%B %e, %Y")%> </h1>
      <table class="table table-striped">
      <thead>
        <tr>
          <th>Event</th>
          <th>Time</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td>  <%= event.name %> </td>
            <td>  <%= event.date_and_time.strftime("%l : %M %P") %> </td>
            <td>  <%= event.location %> </td>
        <%end %>
          </tr>
      </tbody>
    </table>
</div>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :date_and_time %>
    <%= f.datetime_field :date_and_time %>

  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/show.html.erb
  <div class="container">
    <h1 id="datetoday"> Day : <%= @day.strftime("%B %e, %Y")%> </h1>
      <table class="table table-striped">
      <thead>
        <tr>
          <th>Event</th>
          <th>Time</th>
          <th>Location</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td>  <%= event.name %> </td>
            <td>  <%= event.date_and_time.strftime("%l : %M %P") %> </td>
            <td>  <%= event.location %> </td>
          </tr>
        <%end %>
      </tbody>
    </table>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %> -->
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="topnav" id="myTopnav">
    <a href="/calendar">Home</a>
    <a href="/events">Today</a>
    <a href="/events/new">Add Event</a>
    <a href="/">Other</a>
  </div>

    <div class="login">
      <% if user_signed_in? %>
      Logged in as <strong> <%= current_user.email %></strong>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>

        <div class="container">
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>

    </ul>
  </body>
  </html>